import React from 'react';
import { render, screen } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import Dashboard_Locataire from './components/dashboard_locataire/Dashboard_Locataire';

// Mock des modules qui posent problème
jest.mock('./components/dashboard_locataire/Dashboard_Locataire.module.css', () => ({
  sidebar: 'sidebar',
  mainWrapper: 'mainWrapper',
  header: 'header',
  mainContent: 'mainContent',
  welcomeBanner: 'welcomeBanner',
  rentCard: 'rentCard',
  quickActionsGrid: 'quickActionsGrid',
  card: 'card',
  // Ajouter toutes les classes nécessaires
  appLayout: 'appLayout',
  sidebarHeader: 'sidebarHeader',
  logo: 'logo',
  logoIcon: 'logoIcon',
  logoText: 'logoText',
  sidebarNav: 'sidebarNav',
  navSection: 'navSection',
  navSectionTitle: 'navSectionTitle',
  navLink: 'navLink',
  active: 'active',
  navLinkBadge: 'navLinkBadge',
  sidebarUser: 'sidebarUser',
  userCard: 'userCard',
  userAvatar: 'userAvatar',
  userInfo: 'userInfo',
  userName: 'userName',
  userRole: 'userRole',
  verifiedBadge: 'verifiedBadge',
  userMenuBtn: 'userMenuBtn',
  headerLeft: 'headerLeft',
  pageTitle: 'pageTitle',
  headerRight: 'headerRight',
  headerDate: 'headerDate',
  headerBtn: 'headerBtn',
  notificationDot: 'notificationDot',
  welcomeContent: 'welcomeContent',
  welcomeGreeting: 'welcomeGreeting',
  welcomeTitle: 'welcomeTitle',
  welcomeSubtitle: 'welcomeSubtitle',
  welcomeHome: 'welcomeHome',
  homeThumb: 'homeThumb',
  homeDetails: 'homeDetails',
  homeBadge: 'homeBadge',
  homeBadgeDot: 'homeBadgeDot',
  rentCardHeader: 'rentCardHeader',
  rentLabel: 'rentLabel',
  rentStatus: 'rentStatus',
  statusPaid: 'statusPaid',
  statusPending: 'statusPending',
  statusFailed: 'statusFailed',
  rentCardBody: 'rentCardBody',
  rentAmountRow: 'rentAmountRow',
  rentAmount: 'rentAmount',
  rentCountdown: 'rentCountdown',
  countdownLabel: 'countdownLabel',
  countdownValue: 'countdownValue',
  countdownNumber: 'countdownNumber',
  countdownText: 'countdownText',
  rentDueInfo: 'rentDueInfo',
  dueDetail: 'dueDetail',
  dueLabel: 'dueLabel',
  dueValue: 'dueValue',
  rentPaymentMethod: 'rentPaymentMethod',
  paymentIcon: 'paymentIcon',
  paymentInfo: 'paymentInfo',
  paymentLabel: 'paymentLabel',
  paymentValue: 'paymentValue',
  paymentStatus: 'paymentStatus',
  paymentEditBtn: 'paymentEditBtn',
  quickAction: 'quickAction',
  quickActionIcon: 'quickActionIcon',
  iconContact: 'iconContact',
  iconProblem: 'iconProblem',
  iconReceipt: 'iconReceipt',
  iconContract: 'iconContract',
  quickActionContent: 'quickActionContent',
  cardHeader: 'cardHeader',
  cardTitle: 'cardTitle',
  cardAction: 'cardAction',
  cardBody: 'cardBody',
  cardBodyNoPaddingTop: 'cardBodyNoPaddingTop',
  paymentList: 'paymentList',
  paymentItem: 'paymentItem',
  paymentItemIcon: 'paymentItemIcon',
  paid: 'paid',
  failed: 'failed',
  paymentItemDetails: 'paymentItemDetails',
  paymentItemTitle: 'paymentItemTitle',
  paymentItemDate: 'paymentItemDate',
  paymentItemAmount: 'paymentItemAmount',
  paymentItemReceipt: 'paymentItemReceipt',
  agentCard: 'agentCard',
  agentAvatar: 'agentAvatar',
  agentInfo: 'agentInfo',
  agentRole: 'agentRole',
  agentName: 'agentName',
  agentVerified: 'agentVerified',
  agentActions: 'agentActions',
  agentBtn: 'agentBtn',
  primary: 'primary',
  secondary: 'secondary',
  housingGrid: 'housingGrid',
  housingStat: 'housingStat',
  housingStatLabel: 'housingStatLabel',
  housingStatValue: 'housingStatValue',
  notificationList: 'notificationList',
  notificationItem: 'notificationItem',
  unread: 'unread',
  notificationIcon: 'notificationIcon',
  success: 'success',
  info: 'info',
  warning: 'warning',
  notificationContent: 'notificationContent',
  notificationText: 'notificationText',
  notificationTime: 'notificationTime',
  dashboardGrid: 'dashboardGrid',
  dashboardMain: 'dashboardMain',
  dashboardSide: 'dashboardSide',
  dashboardSection: 'dashboardSection',
  dashboardSectionTitle: 'dashboardSectionTitle',
  dashboardSectionContent: 'dashboardSectionContent',
}));

// Mock des icônes
jest.mock('lucide-react', () => ({
  Home: () => <span>Home Icon</span>,
  Menu: () => <span>Menu Icon</span>,
  X: () => <span>X Icon</span>,
  Search: () => <span>Search Icon</span>,
  Bell: () => <span>Bell Icon</span>,
  Settings: () => <span>Settings Icon</span>,
  MoreVertical: () => <span>MoreVertical Icon</span>,
  Check: () => <span>Check Icon</span>,
  BadgeCheck: () => <span>BadgeCheck Icon</span>,
  Building: () => <span>Building Icon</span>,
  AlertTriangle: () => <span>AlertTriangle Icon</span>,
  Download: () => <span>Download Icon</span>,
  ChevronRight: () => <span>ChevronRight Icon</span>,
  User: () => <span>User Icon</span>,
  Phone: () => <span>Phone Icon</span>,
  Clock: () => <span>Clock Icon</span>,
}));

describe('Dashboard_Locataire Component', () => {
  test('renders dashboard layout', () => {
    render(
      <BrowserRouter>
        <Dashboard_Locataire />
      </BrowserRouter>
    );

    // Vérifie qu'un élément du tableau de bord est rendu
    const sidebarElement = screen.getByText(/ImmoGN/i);
    expect(sidebarElement).toBeInTheDocument();
  });
});